# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5eb13cdb7c56daf4bd54f8d5108aa7272e7486d2d158fc5bf6eebcfebb1280769f388752597cc93ac35914584bee1883a7410ec72fdc458c26129483564d1814

test:
  secret_key_base: 86d41c32b6816de8a530e9b2e50918872af398edde44954df89c50feff9ec83378d1f445fd05caf1b51ddf239005397f9dcb10d1ae7bceca8b5c5800b6711569

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
